# Generated by Django 3.1.7 on 2021-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210304_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='shop',
            field=models.CharField(choices=[('shop1', 'VASANTHAM HARDWARES'), ('shop2', 'VIJAY PLYWOODS'), ('shop3', 'SHANTI PLYWOODS'), ('shop4', 'VASANTHAM OFFICE')], default='shop1', max_length=6),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='give_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='rental_month',
            field=models.DateField(),
        ),
    ]
