# Generated by Django 3.1.7 on 2021-03-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210304_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='shop',
            field=models.CharField(choices=[('Vasantham Hardwares', 'VASANTHAM HARDWARES'), ('Vijay Plywoods', 'VIJAY PLYWOODS'), ('Shanti Plywoods', 'SHANTI PLYWOODS'), ('Vasantham Office', 'VASANTHAM OFFICE')], default='shop1', max_length=100),
        ),
    ]
