# Generated by Django 3.1.7 on 2021-03-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210304_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='shop',
            field=models.CharField(choices=[('Vasantham Hardwares', 'VASANTHAM HARDWARES'), ('Vijay Plywoods', 'VIJAY PLYWOODS'), ('Shanti Plywoods', 'SHANTI PLYWOODS'), ('Vasantham Office', 'VASANTHAM OFFICE')], default='Vasantham Hardwares', max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='status',
            field=models.CharField(choices=[('Received', 'RECEIVED'), ('Pending', 'PENDING')], default='Pending', max_length=100),
        ),
    ]
