# Generated by Django 3.1.7 on 2021-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210304_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='give_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
