# Generated by Django 3.1.7 on 2021-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210305_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_n', models.CharField(choices=[('Vasantham Hardwares', 'VASANTHAM HARDWARES'), ('Vijay Plywoods', 'VIJAY PLYWOODS'), ('Shanti Plywoods', 'SHANTI PLYWOODS'), ('Vasantham Office', 'VASANTHAM OFFICE')], default='Vasantham Hardwares', max_length=100)),
                ('tenant_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='tenant_name',
        ),
    ]
