# Generated by Django 3.1.7 on 2021-03-05 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210305_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard_details',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tenant_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
