# Generated by Django 3.1.7 on 2021-03-05 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20210305_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='shop_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
