# Generated by Django 3.1.7 on 2021-03-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_details_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='owner_name',
        ),
    ]
