# Generated by Django 3.1.7 on 2021-03-05 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_remove_details_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='furnished',
            field=models.CharField(choices=[('Fully furnished', 'FULLY FURNISHED'), ('Semi furnished', 'SEMI FURNISHED'), ('Unfurnished', 'UNFURNISHED')], default='Unfurnished', max_length=100),
        ),
    ]
